CREATE TABLE `batchlist` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ARCHIVE` tinyint(1) DEFAULT NULL,
  `LIST_NAME` varchar(255) DEFAULT NULL,
  `time` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LIST_NAME` (`LIST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;